server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file://D:/Projects/Funchive/funchive-config-repo
          search-paths: "{application}"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

