server:
  port: 8888

spring:
  application:
    name: funchive-config-server

  cloud:
    config:
      server:
        git:
          uri: file:./config-repo/{application}
          search-paths: "{application}"

